-- Delete existing data and reset auto-increment
DELETE FROM voters_record;

-- Drop the primary key and recreate it
ALTER TABLE voters_record DROP PRIMARY KEY;
ALTER TABLE voters_record MODIFY COLUMN NO INT AUTO_INCREMENT PRIMARY KEY;

-- Sample data for all barangays
INSERT INTO voters_record (VOTERS_NAME, PRECINCT_NO, BARANGAY, SITIO, RICE_BENEFICIARY_1, RICE_BENEFICIARY_HEAD_2, BARANGAY_LEADER_3, LEVEL_1, LEVEL_2, LEVEL_3, REMARKS, RBH_NAME, BL_NAME) VALUES
-- ADLAWAN
('SANTOS, MARIA', '101A', 'ADLAWAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active voter', 'SANTOS, MARIA', NULL),
('CRUZ, JUAN', '101A', 'ADLAWAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, MARIA', 'CRUZ, JUAN'),

-- BAGO
('REYES, ANTONIO', '102B', 'BAGO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior citizen', 'REYES, ANTONIO', NULL),
('GARCIA, ELENA', '102B', 'BAGO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'REYES, ANTONIO', 'GARCIA, ELENA'),

-- BALIJUAGAN
('TORRES, RAMON', '103A', 'BALIJUAGAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'TORRES, RAMON', NULL),
('LOPEZ, CARMEN', '103A', 'BALIJUAGAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'TORRES, RAMON', 'LOPEZ, CARMEN'),

-- BANICA
('FERNANDEZ, JOSE', '104B', 'BANICA', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'FERNANDEZ, JOSE', NULL),
('SANTOS, ANA', '104B', 'BANICA', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, JOSE', 'SANTOS, ANA'),

-- BARRA
('GONZALES, PEDRO', '105A', 'BARRA', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'GONZALES, PEDRO', NULL),
('MARTINEZ, ROSA', '105A', 'BARRA', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, PEDRO', 'MARTINEZ, ROSA'),

-- BATO
('RODRIGUEZ, MANUEL', '106B', 'BATO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'RODRIGUEZ, MANUEL', NULL),
('CRUZ, MARIA', '106B', 'BATO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, MANUEL', 'CRUZ, MARIA'),

-- BAYBAY
('PEREZ, RICARDO', '107A', 'BAYBAY', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'PEREZ, RICARDO', NULL),
('SANTOS, LUCIA', '107A', 'BAYBAY', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'PEREZ, RICARDO', 'SANTOS, LUCIA'),

-- BOLO
('REYES, FRANCISCO', '108B', 'BOLO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'REYES, FRANCISCO', NULL),
('GARCIA, TERESA', '108B', 'BOLO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'REYES, FRANCISCO', 'GARCIA, TERESA'),

-- CABUGAO
('TORRES, EDUARDO', '109A', 'CABUGAO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'TORRES, EDUARDO', NULL),
('LOPEZ, PATRICIA', '109A', 'CABUGAO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'TORRES, EDUARDO', 'LOPEZ, PATRICIA'),

-- CAGAY
('FERNANDEZ, MIGUEL', '110B', 'CAGAY', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'FERNANDEZ, MIGUEL', NULL),
('SANTOS, CLARA', '110B', 'CAGAY', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, MIGUEL', 'SANTOS, CLARA'),

-- COGON
('GONZALES, ROBERTO', '111A', 'COGON', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'GONZALES, ROBERTO', NULL),
('MARTINEZ, VICTORIA', '111A', 'COGON', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, ROBERTO', 'MARTINEZ, VICTORIA'),

-- CULAJAO
('RODRIGUEZ, ANTONIO', '112B', 'CULAJAO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'RODRIGUEZ, ANTONIO', NULL),
('CRUZ, SOFIA', '112B', 'CULAJAO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, ANTONIO', 'CRUZ, SOFIA'),

-- CULASI
('MENDOZA, LUIS', '113A', 'CULASI', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'MENDOZA, LUIS', NULL),
('REYES, ISABEL', '113A', 'CULASI', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'MENDOZA, LUIS', 'REYES, ISABEL'),

-- DAYAO
('SANTOS, PABLO', '114B', 'DAYAO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'SANTOS, PABLO', NULL),
('GARCIA, ROSA', '114B', 'DAYAO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, PABLO', 'GARCIA, ROSA'),

-- DINGINAN
('CRUZ, RAFAEL', '115A', 'DINGINAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'CRUZ, RAFAEL', NULL),
('TORRES, MARIA', '115A', 'DINGINAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'CRUZ, RAFAEL', 'TORRES, MARIA'),

-- DUMOLOG
('REYES, MANUEL', '116B', 'DUMOLOG', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'REYES, MANUEL', NULL),
('LOPEZ, ANA', '116B', 'DUMOLOG', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'REYES, MANUEL', 'LOPEZ, ANA'),

-- GABU-AN
('FERNANDEZ, CARLOS', '117A', 'GABU-AN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'FERNANDEZ, CARLOS', NULL),
('SANTOS, TERESA', '117A', 'GABU-AN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, CARLOS', 'SANTOS, TERESA'),

-- INZO ARNALDO VILLAGE
('GONZALES, ANTONIO', '118B', 'INZO ARNALDO VILLAGE', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'GONZALES, ANTONIO', NULL),
('MARTINEZ, CLARA', '118B', 'INZO ARNALDO VILLAGE', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, ANTONIO', 'MARTINEZ, CLARA'),

-- JUMAGUICJIC
('RODRIGUEZ, JOSE', '119A', 'JUMAGUICJIC', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'RODRIGUEZ, JOSE', NULL),
('CRUZ, PATRICIA', '119A', 'JUMAGUICJIC', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, JOSE', 'CRUZ, PATRICIA'),

-- POB I to POB XI
('DELA CRUZ, JUAN', '201A', 'POB I', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'DELA CRUZ, JUAN', NULL),
('SANTOS, MARIA', '201A', 'POB I', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'DELA CRUZ, JUAN', 'SANTOS, MARIA'),

('GARCIA, PEDRO', '202B', 'POB II', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'GARCIA, PEDRO', NULL),
('REYES, ANA', '202B', 'POB II', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GARCIA, PEDRO', 'REYES, ANA'),

('LOPEZ, RAMON', '203A', 'POB III', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'LOPEZ, RAMON', NULL),
('TORRES, ELENA', '203A', 'POB III', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, RAMON', 'TORRES, ELENA'),

('SANTOS, RICARDO', '204A', 'POB IV', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'SANTOS, RICARDO', NULL),
('GARCIA, VICTORIA', '204A', 'POB IV', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, RICARDO', 'GARCIA, VICTORIA'),

('LOPEZ, EDUARDO', '205B', 'POB V', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'LOPEZ, EDUARDO', NULL),
('TORRES, SOFIA', '205B', 'POB V', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, EDUARDO', 'TORRES, SOFIA'),

('FERNANDEZ, RAMON', '206A', 'POB VI', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'FERNANDEZ, RAMON', NULL),
('REYES, LUCIA', '206A', 'POB VI', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, RAMON', 'REYES, LUCIA'),

('GONZALES, MIGUEL', '207B', 'POB VII', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'GONZALES, MIGUEL', NULL),
('MARTINEZ, CARMEN', '207B', 'POB VII', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, MIGUEL', 'MARTINEZ, CARMEN'),

('RODRIGUEZ, PABLO', '208A', 'POB VIII', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'RODRIGUEZ, PABLO', NULL),
('CRUZ, ISABEL', '208A', 'POB VIII', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, PABLO', 'CRUZ, ISABEL'),

('SANTOS, LUIS', '209B', 'POB IX', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'SANTOS, LUIS', NULL),
('GARCIA, MARIA', '209B', 'POB IX', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, LUIS', 'GARCIA, MARIA'),

('LOPEZ, CARLOS', '210A', 'POB X', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'LOPEZ, CARLOS', NULL),
('TORRES, ANA', '210A', 'POB X', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, CARLOS', 'TORRES, ANA'),

('FERNANDEZ, ANTONIO', '211B', 'POB XI', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'FERNANDEZ, ANTONIO', NULL),
('REYES, TERESA', '211B', 'POB XI', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, ANTONIO', 'REYES, TERESA'),

-- Remaining barangays
('GONZALES, MANUEL', '301A', 'PUNTA COGON', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'GONZALES, MANUEL', NULL),
('MARTINEZ, PATRICIA', '301A', 'PUNTA COGON', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, MANUEL', 'MARTINEZ, PATRICIA'),

('RODRIGUEZ, RICARDO', '302B', 'PUNTA TABUC', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'RODRIGUEZ, RICARDO', NULL),
('CRUZ, VICTORIA', '302B', 'PUNTA TABUC', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, RICARDO', 'CRUZ, VICTORIA'),

('SANTOS, EDUARDO', '303A', 'SAN JOSE', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'SANTOS, EDUARDO', NULL),
('GARCIA, SOFIA', '303A', 'SAN JOSE', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, EDUARDO', 'GARCIA, SOFIA'),

('LOPEZ, PABLO', '304B', 'SIBAGUAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'LOPEZ, PABLO', NULL),
('TORRES, LUCIA', '304B', 'SIBAGUAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, PABLO', 'TORRES, LUCIA'),

('FERNANDEZ, LUIS', '305A', 'TALON', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'FERNANDEZ, LUIS', NULL),
('REYES, CARMEN', '305A', 'TALON', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, LUIS', 'REYES, CARMEN'),

('GONZALES, MIGUEL', '306B', 'TANQUE', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'GONZALES, MIGUEL', NULL),
('MARTINEZ, ISABEL', '306B', 'TANQUE', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, MIGUEL', 'MARTINEZ, ISABEL'),

('RODRIGUEZ, JOSE', '307A', 'TIZA', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'RODRIGUEZ, JOSE', NULL),
('CRUZ, CARMEN', '307A', 'TIZA', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, JOSE', 'CRUZ, CARMEN'),

-- Additional entries for remaining barangays
('SANTOS, MANUEL', '401A', 'LANOT', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'SANTOS, MANUEL', NULL),
('GARCIA, PATRICIA', '401A', 'LANOT', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, MANUEL', 'GARCIA, PATRICIA'),

('LOPEZ, RICARDO', '402B', 'LAWA-AN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'LOPEZ, RICARDO', NULL),
('TORRES, VICTORIA', '402B', 'LAWA-AN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, RICARDO', 'TORRES, VICTORIA'),

('FERNANDEZ, EDUARDO', '403A', 'LIBAS', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'FERNANDEZ, EDUARDO', NULL),
('REYES, SOFIA', '403A', 'LIBAS', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, EDUARDO', 'REYES, SOFIA'),

('GONZALES, PABLO', '404B', 'LIONG', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'GONZALES, PABLO', NULL),
('MARTINEZ, LUCIA', '404B', 'LIONG', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, PABLO', 'MARTINEZ, LUCIA'),

('RODRIGUEZ, CARLOS', '405A', 'LOCTUGAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'RODRIGUEZ, CARLOS', NULL),
('CRUZ, ANA', '405A', 'LOCTUGAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, CARLOS', 'CRUZ, ANA'),

('SANTOS, ANTONIO', '406B', 'LONOY', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'SANTOS, ANTONIO', NULL),
('GARCIA, TERESA', '406B', 'LONOY', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, ANTONIO', 'GARCIA, TERESA'),

('LOPEZ, MIGUEL', '407A', 'MILIBILI', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'LOPEZ, MIGUEL', NULL),
('TORRES, CLARA', '407A', 'MILIBILI', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, MIGUEL', 'TORRES, CLARA'),

('FERNANDEZ, JOSE', '408B', 'MONGPONG', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'FERNANDEZ, JOSE', NULL),
('REYES, PATRICIA', '408B', 'MONGPONG', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, JOSE', 'REYES, PATRICIA'),

('GONZALES, RAMON', '409A', 'OLOTAYAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'GONZALES, RAMON', NULL),
('MARTINEZ, VICTORIA', '409A', 'OLOTAYAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, RAMON', 'MARTINEZ, VICTORIA'); 