-- Sample data for voters_record table
INSERT INTO voters_record (VOTERS_NAME, PRECINCT_NO, BARANGAY, SITIO, RICE_BENEFICIARY_1, RICE_BENEFICIARY_HEAD_2, BARANGAY_LEADER_3, LEVEL_1, LEVEL_2, LEVEL_3, REMARKS, RBH_NAME, BL_NAME) VALUES
-- ADLAWAN
('SANTOS, MARIA', '101A', 'ADLAWAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active voter', 'SANTOS, MARIA', NULL),
('CRUZ, JUAN', '101A', 'ADLAWAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, MARIA', 'CRUZ, JUAN'),

-- BAGO
('REYES, ANTONIO', '102B', 'BAGO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior citizen', 'REYES, ANTONIO', NULL),
('GARCIA, ELENA', '102B', 'BAGO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'REYES, ANTONIO', 'GARCIA, ELENA'),

-- BALIJUAGAN
('TORRES, RAMON', '103A', 'BALIJUAGAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'TORRES, RAMON', NULL),
('LOPEZ, CARMEN', '103A', 'BALIJUAGAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'TORRES, RAMON', 'LOPEZ, CARMEN'),

-- BANICA
('FERNANDEZ, JOSE', '104B', 'BANICA', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'FERNANDEZ, JOSE', NULL),
('SANTOS, ANA', '104B', 'BANICA', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, JOSE', 'SANTOS, ANA'),

-- BARRA
('GONZALES, PEDRO', '105A', 'BARRA', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'GONZALES, PEDRO', NULL),
('MARTINEZ, ROSA', '105A', 'BARRA', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, PEDRO', 'MARTINEZ, ROSA'),

-- BATO
('RODRIGUEZ, MANUEL', '106B', 'BATO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'RODRIGUEZ, MANUEL', NULL),
('CRUZ, MARIA', '106B', 'BATO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, MANUEL', 'CRUZ, MARIA'),

-- BAYBAY
('PEREZ, RICARDO', '107A', 'BAYBAY', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'PEREZ, RICARDO', NULL),
('SANTOS, LUCIA', '107A', 'BAYBAY', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'PEREZ, RICARDO', 'SANTOS, LUCIA'),

-- BOLO
('REYES, FRANCISCO', '108B', 'BOLO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'REYES, FRANCISCO', NULL),
('GARCIA, TERESA', '108B', 'BOLO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'REYES, FRANCISCO', 'GARCIA, TERESA'),

-- CABUGAO
('TORRES, EDUARDO', '109A', 'CABUGAO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'TORRES, EDUARDO', NULL),
('LOPEZ, PATRICIA', '109A', 'CABUGAO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'TORRES, EDUARDO', 'LOPEZ, PATRICIA'),

-- CAGAY
('FERNANDEZ, MIGUEL', '110B', 'CAGAY', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'FERNANDEZ, MIGUEL', NULL),
('SANTOS, CLARA', '110B', 'CAGAY', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, MIGUEL', 'SANTOS, CLARA'),

-- Add more entries for other barangays following the same pattern...
-- COGON
('GONZALES, ROBERTO', '111A', 'COGON', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'GONZALES, ROBERTO', NULL),
('MARTINEZ, VICTORIA', '111A', 'COGON', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, ROBERTO', 'MARTINEZ, VICTORIA'),

-- CULAJAO
('RODRIGUEZ, ANTONIO', '112B', 'CULAJAO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'RODRIGUEZ, ANTONIO', NULL),
('CRUZ, SOFIA', '112B', 'CULAJAO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, ANTONIO', 'CRUZ, SOFIA'),

-- Continue with remaining barangays...
-- POB I to POB XI
('DELA CRUZ, JUAN', '201A', 'POB I', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'DELA CRUZ, JUAN', NULL),
('SANTOS, MARIA', '201A', 'POB I', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'DELA CRUZ, JUAN', 'SANTOS, MARIA'),

('GARCIA, PEDRO', '202B', 'POB II', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'GARCIA, PEDRO', NULL),
('REYES, ANA', '202B', 'POB II', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GARCIA, PEDRO', 'REYES, ANA'),

('LOPEZ, RAMON', '203A', 'POB III', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'LOPEZ, RAMON', NULL),
('TORRES, ELENA', '203A', 'POB III', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, RAMON', 'TORRES, ELENA'),

-- Add remaining POB areas...

-- Final barangays
('MENDOZA, CARLOS', '301A', 'TANZA', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'MENDOZA, CARLOS', NULL),
('SANTOS, LUCIA', '301A', 'TANZA', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'MENDOZA, CARLOS', 'SANTOS, LUCIA'),

('CRUZ, ROBERTO', '302B', 'TIZA', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'CRUZ, ROBERTO', NULL),
('REYES, CARMEN', '302B', 'TIZA', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'CRUZ, ROBERTO', 'REYES, CARMEN'); 