-- Continue sample data for remaining barangays
INSERT INTO voters_record (VOTERS_NAME, PRECINCT_NO, BARANGAY, SITIO, RICE_BENEFICIARY_1, RICE_BENEFICIARY_HEAD_2, BARANGAY_LEADER_3, LEVEL_1, LEVEL_2, LEVEL_3, REMARKS, RBH_NAME, BL_NAME) VALUES
-- CULASI
('MENDOZA, LUIS', '113A', 'CULASI', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'MENDOZA, LUIS', NULL),
('REYES, ISABEL', '113A', 'CULASI', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'MENDOZA, LUIS', 'REYES, ISABEL'),

-- DAYAO
('SANTOS, PABLO', '114B', 'DAYAO', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'SANTOS, PABLO', NULL),
('GARCIA, ROSA', '114B', 'DAYAO', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, PABLO', 'GARCIA, ROSA'),

-- DINGINAN
('CRUZ, RAFAEL', '115A', 'DINGINAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'CRUZ, RAFAEL', NULL),
('TORRES, MARIA', '115A', 'DINGINAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'CRUZ, RAFAEL', 'TORRES, MARIA'),

-- DUMOLOG
('REYES, MANUEL', '116B', 'DUMOLOG', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'REYES, MANUEL', NULL),
('LOPEZ, ANA', '116B', 'DUMOLOG', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'REYES, MANUEL', 'LOPEZ, ANA'),

-- GABU-AN
('FERNANDEZ, CARLOS', '117A', 'GABU-AN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'FERNANDEZ, CARLOS', NULL),
('SANTOS, TERESA', '117A', 'GABU-AN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, CARLOS', 'SANTOS, TERESA'),

-- INZO ARNALDO VILLAGE
('GONZALES, ANTONIO', '118B', 'INZO ARNALDO VILLAGE', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'GONZALES, ANTONIO', NULL),
('MARTINEZ, CLARA', '118B', 'INZO ARNALDO VILLAGE', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, ANTONIO', 'MARTINEZ, CLARA'),

-- JUMAGUICJIC
('RODRIGUEZ, JOSE', '119A', 'JUMAGUICJIC', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'RODRIGUEZ, JOSE', NULL),
('CRUZ, PATRICIA', '119A', 'JUMAGUICJIC', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, JOSE', 'CRUZ, PATRICIA'),

-- Continue with POB areas...
-- POB IV
('SANTOS, RICARDO', '204A', 'POB IV', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'SANTOS, RICARDO', NULL),
('GARCIA, VICTORIA', '204A', 'POB IV', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, RICARDO', 'GARCIA, VICTORIA'),

-- POB V
('LOPEZ, EDUARDO', '205B', 'POB V', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'LOPEZ, EDUARDO', NULL),
('TORRES, SOFIA', '205B', 'POB V', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, EDUARDO', 'TORRES, SOFIA'),

-- POB VI to POB XI
('FERNANDEZ, RAMON', '206A', 'POB VI', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'FERNANDEZ, RAMON', NULL),
('REYES, LUCIA', '206A', 'POB VI', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, RAMON', 'REYES, LUCIA'),

('GONZALES, MIGUEL', '207B', 'POB VII', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'GONZALES, MIGUEL', NULL),
('MARTINEZ, CARMEN', '207B', 'POB VII', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, MIGUEL', 'MARTINEZ, CARMEN'),

('RODRIGUEZ, PABLO', '208A', 'POB VIII', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'RODRIGUEZ, PABLO', NULL),
('CRUZ, ISABEL', '208A', 'POB VIII', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, PABLO', 'CRUZ, ISABEL'),

('SANTOS, LUIS', '209B', 'POB IX', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'SANTOS, LUIS', NULL),
('GARCIA, MARIA', '209B', 'POB IX', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, LUIS', 'GARCIA, MARIA'),

('LOPEZ, CARLOS', '210A', 'POB X', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'LOPEZ, CARLOS', NULL),
('TORRES, ANA', '210A', 'POB X', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, CARLOS', 'TORRES, ANA'),

('FERNANDEZ, ANTONIO', '211B', 'POB XI', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'FERNANDEZ, ANTONIO', NULL),
('REYES, TERESA', '211B', 'POB XI', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, ANTONIO', 'REYES, TERESA'),

-- Remaining barangays
('GONZALES, MANUEL', '301A', 'PUNTA COGON', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'GONZALES, MANUEL', NULL),
('MARTINEZ, PATRICIA', '301A', 'PUNTA COGON', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, MANUEL', 'MARTINEZ, PATRICIA'),

('RODRIGUEZ, RICARDO', '302B', 'PUNTA TABUC', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'PWD', 'RODRIGUEZ, RICARDO', NULL),
('CRUZ, VICTORIA', '302B', 'PUNTA TABUC', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'RODRIGUEZ, RICARDO', 'CRUZ, VICTORIA'),

('SANTOS, EDUARDO', '303A', 'SAN JOSE', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'SANTOS, EDUARDO', NULL),
('GARCIA, SOFIA', '303A', 'SAN JOSE', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'SANTOS, EDUARDO', 'GARCIA, SOFIA'),

('LOPEZ, PABLO', '304B', 'SIBAGUAN', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Active', 'LOPEZ, PABLO', NULL),
('TORRES, LUCIA', '304B', 'SIBAGUAN', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'LOPEZ, PABLO', 'TORRES, LUCIA'),

('FERNANDEZ, LUIS', '305A', 'TALON', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, NULL, 'FERNANDEZ, LUIS', NULL),
('REYES, CARMEN', '305A', 'TALON', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'FERNANDEZ, LUIS', 'REYES, CARMEN'),

('GONZALES, MIGUEL', '306B', 'TANQUE', 'ZONE 1', '1', '1', NULL, '1', NULL, NULL, 'Senior', 'GONZALES, MIGUEL', NULL),
('MARTINEZ, ISABEL', '306B', 'TANQUE', 'ZONE 2', '1', NULL, '1', '1', NULL, NULL, NULL, 'GONZALES, MIGUEL', 'MARTINEZ, ISABEL'); 